# Generated by Django 4.2.5 on 2026-09-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others'), ('P', 'Prefer not to say')], max_length=1),
        ),
    ]
