# Generated by Django 4.2.5 on 2026-09-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_teammember_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Registration Deadline'),
        ),
    ]
