# Generated by Django 4.2.5 on 2026-10-02 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_city_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityEventConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registration_open', models.BooleanField(default=True, help_text='Uncheck to close registration for this event in this city only. Other cities are not affected.', verbose_name='Registration Open')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_configs', to='core.city')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_configs', to='core.event')),
            ],
            options={
                'verbose_name': 'City-Event Registration Config',
                'verbose_name_plural': 'City-Event Registration Configs',
                'unique_together': {('city', 'event')},
            },
        ),
    ]
