# Generated by Django 4.2.5 on 2026-10-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_cityeventconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityeventconfig',
            name='deadline',
            field=models.DateField(blank=True, help_text="Override the global registration deadline for this competition in this city only. Leave blank to use the event's default deadline.", null=True, verbose_name='City-Specific Registration Deadline'),
        ),
        migrations.AddField(
            model_name='cityeventconfig',
            name='event_date',
            field=models.DateField(blank=True, help_text="Override the global event date for this competition in this city only. Leave blank to use the event's default date.", null=True, verbose_name='City-Specific Event Date'),
        ),
    ]
