# Generated by Django 4.2.5 on 2026-10-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cityeventconfig_deadline_cityeventconfig_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='custom_date',
            field=models.CharField(blank=True, help_text="Custom display text like '10-11 Oct'. Overrides standard date formatting.", max_length=60, null=True, verbose_name='Custom Date (e.g. 10-11 Oct)'),
        ),
        migrations.AddField(
            model_name='city',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event End Date (Optional)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='time',
            field=models.DateField(blank=True, null=True, verbose_name='Event Start Date'),
        ),
    ]
