"""
Django settings for cityelimination project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment mode
PROD = os.environ.get('prod', 'false').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
# In prod this MUST come from the environment - no hardcoded fallback allowed.
if PROD:
    SECRET_KEY = os.environ['SECRET_KEY']  # raises KeyError loudly if missing - good, fail fast
else:
    SECRET_KEY = os.environ.get(
        'SECRET_KEY',
        'django-insecure-)zfwsh_jx=vqympmk#pj_q-%t2_14-m+iq@_#)1_j9zg#q^#@q'
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not PROD

if PROD:
    ALLOWED_HOSTS = os.environ.get(
        'ALLOWED_HOSTS',
        'prelims.alcheringa.co.in,ceportal.alcheringa.co.in'
    ).split(',')
else:
    ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "minio_storage",
    "formtools",
    'import_export'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cityelimination.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cityelimination.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
#
# FIXED: previously PROD branch ignored DATABASE_URL entirely and hardcoded
# sqlite even in production. Now both branches respect DATABASE_URL, and
# prod requires it to be explicitly set (no silent sqlite fallback in prod).
if PROD:
    DATABASES = {
        'default': dj_database_url.config(
            env='DATABASE_URL',
            conn_max_age=600,
            ssl_require=True,
        )
    }
    if not DATABASES['default']:
        raise RuntimeError("DATABASE_URL must be set when prod=true")
else:
    DATABASES = {
        'default': dj_database_url.config(
            default='sqlite:///db.sqlite3',
            conn_max_age=600,
            ssl_require=False,
        )
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

# Storage Configuration
if PROD:
    # Production - MinIO storage
    DEFAULT_FILE_STORAGE = "minio_storage.storage.MinioMediaStorage"
    STATICFILES_STORAGE = "minio_storage.storage.MinioStaticStorage"

    MINIO_STORAGE_ENDPOINT = os.environ['minio_endpoint']
    MINIO_STORAGE_ACCESS_KEY = os.environ['minio_access']
    MINIO_STORAGE_SECRET_KEY = os.environ['minio_secret']
    MINIO_STORAGE_USE_HTTPS = True

    MINIO_STORAGE_MEDIA_BUCKET_NAME = 'alcherce27media'
    MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True
    MINIO_STORAGE_STATIC_BUCKET_NAME = 'alcherce27static'
    MINIO_STORAGE_AUTO_CREATE_STATIC_BUCKET = True
else:
    # Development - local storage
    STATICFILES_DIRS = [BASE_DIR / "static"]
    STATIC_ROOT = BASE_DIR / "staticfiles"
    MEDIA_ROOT = BASE_DIR / "media"

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
if PROD and not EMAIL_HOST_PASSWORD:
    raise RuntimeError("EMAIL_HOST_PASSWORD must be set when prod=true")

# Other Settings
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SECURE_REFERRER_POLICY = "no-referrer-when-downgrade"

# CSRF Trusted Origins
#
# FIXED: this block was inverted in the original file - it set the real
# production domains as trusted only when PROD was False, and set
# 127.0.0.1:8000 as trusted when PROD was True. That meant real prod
# traffic from prelims.alcheringa.co.in / ceportal.alcheringa.co.in
# would fail CSRF checks in actual production.
if PROD:
    CSRF_TRUSTED_ORIGINS = [
        'https://prelims.alcheringa.co.in',
        'http://prelims.alcheringa.co.in',
        'http://ceportal.alcheringa.co.in',
        'https://ceportal.alcheringa.co.in',
    ]
else:
    CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000']

# Additional production security hardening
if PROD:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'minio_storage': {
            'handlers': ['console'],
            'level': 'DEBUG' if not PROD else 'INFO',
            'propagate': True,
        },
    },
}